from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from llvm_hackme.github import GitHubClient, IssueComment
from llvm_hackme.models import BugKind, CommentState, PullRequestUpdate, Reproducer
from llvm_hackme.state import StateStore

if TYPE_CHECKING:
    pass

LOGGER = logging.getLogger(__name__)

COMMENT_FIRST_LINE = "The following correctness issue was found by llvm-hackme."

_MARKER_PREFIX = "<!-- llvm-hackme-"


def _make_run_line(command: list[str]) -> str:
    pass_arg = "-passes=?"
    for arg in command:
        if arg.startswith("-passes="):
            pass_arg = arg
            break
    run = f"; RUN: opt {pass_arg} -S"
    return run


def make_comment_body(
    state: CommentState,
    reproducer: Reproducer | None,
) -> str:
    lines: list[str] = [COMMENT_FIRST_LINE, ""]

    lines.append(f"{_MARKER_PREFIX}state: {state.value} -->")

    if reproducer is not None:
        lines.append(f"{_MARKER_PREFIX}baseline: {reproducer.baseline_revision} -->")
        lines.append(f"{_MARKER_PREFIX}head-sha: {reproducer.pr_head_sha} -->")
        lines.append(f"{_MARKER_PREFIX}patch-sha256: {reproducer.patch_sha256} -->")
        lines.append(f"{_MARKER_PREFIX}kind: {reproducer.kind.value} -->")

    lines.append("")
    lines.append(
        "This comment is generated by an automated correctness checking service "
        "designed to help identify critical correctness bugs (opt crashes or "
        "Alive2 miscompilations) and improve PR review efficiency under limited "
        "reviewer bandwidth."
    )
    lines.append("")

    if state == CommentState.BUG_FOUND and reproducer is not None:
        lines.append("## Reproducer")
        lines.append("")
        lines.append(f"**Kind**: {reproducer.kind.value}")
        lines.append("")

        if reproducer.source_content:
            run_line = _make_run_line(reproducer.command)
            lines.append("**IR Reproducer**:")
            lines.append("```llvm")
            lines.append(run_line)
            lines.append(reproducer.source_content.strip())
            lines.append("```")
            lines.append("")

        if reproducer.kind == BugKind.CRASH and reproducer.stacktrace:
            lines.append("**Stacktrace**:")
            lines.append("```")
            lines.append(reproducer.stacktrace.strip())
            lines.append("```")
            lines.append("")

        if (
            reproducer.kind == BugKind.MISCOMPILATION
            and reproducer.alive2_counterexample
        ):
            lines.append("**Alive2 Counterexample**:")
            lines.append("```")
            lines.append(reproducer.alive2_counterexample.strip())
            lines.append("```")
            lines.append("")

        lines.append(f"**Baseline Revision**: `{reproducer.baseline_revision}`")
        lines.append(f"**PR Head SHA**: `{reproducer.pr_head_sha}`")
        lines.append(f"**Patch SHA256**: `{reproducer.patch_sha256}`")

    elif state == CommentState.STILL_REPRODUCES and reproducer is not None:
        lines.append("## Status: Previously reported issue still reproduces")
        lines.append("")
        lines.append(
            f"The correctness bug ({reproducer.kind.value}) previously reported "
            "still reproduces with the current PR update."
        )
        lines.append(f"**PR Head SHA**: `{reproducer.pr_head_sha}`")
        lines.append(f"**Patch SHA256**: `{reproducer.patch_sha256}`")

    elif state == CommentState.NO_ISSUE_FOUND_FOR_CURRENT_PATCH:
        lines.append("## Status: No new correctness issue found")
        lines.append("")
        lines.append(
            "Fuzzing did not identify any new correctness bugs (opt crashes or "
            "Alive2 miscompilations) for the current patch."
        )

    return "\n".join(lines) + "\n"


def find_llvm_hackme_comment(
    comments: list[IssueComment], service_login: str
) -> IssueComment | None:
    for comment in comments:
        if comment.author_login != service_login:
            continue
        first_line = comment.body.strip().split("\n", 1)[0].strip()
        if first_line == COMMENT_FIRST_LINE:
            return comment
    return None


REVIEW_REQUEST_BODY = (
    "A correctness issue was identified by llvm-hackme. "
    "Please see the [issue comment]({comment_url}) for details."
)


async def report_result(
    github: GitHubClient,
    state: StateStore,
    pr_update: PullRequestUpdate,
    reproducer: Reproducer | None,
    baseline_revision: str,
    service_login: str,
) -> None:
    stored = state.get_pull_state(pr_update.pr.number)

    if reproducer is not None and reproducer.baseline_revision != baseline_revision:
        reproducer = Reproducer(
            kind=reproducer.kind,
            source_path=reproducer.source_path,
            command=reproducer.command,
            baseline_revision=baseline_revision,
            pr_head_sha=reproducer.pr_head_sha,
            patch_sha256=reproducer.patch_sha256,
            stacktrace=reproducer.stacktrace,
            alive2_counterexample=reproducer.alive2_counterexample,
            source_content=reproducer.source_content,
        )

    existing_comments = await github.list_issue_comments(pr_update.pr.number)
    existing = find_llvm_hackme_comment(existing_comments, service_login)

    if existing is not None:
        if stored.comment_id is None:
            state.save_comment(pr_update.pr.number, existing.id, existing.html_url)

        old_reproducer = stored.reproducer
        if reproducer is not None:
            state.save_reproducer(pr_update.pr.number, reproducer)
            if old_reproducer is not None and old_reproducer.kind == reproducer.kind:
                body = make_comment_body(CommentState.STILL_REPRODUCES, reproducer)
                await github.update_issue_comment(existing.id, body)
                LOGGER.info(
                    "Updated existing comment for PR #%s (still_reproduces)",
                    pr_update.pr.number,
                )
                return

            body = make_comment_body(CommentState.BUG_FOUND, reproducer)
            updated = await github.update_issue_comment(existing.id, body)
            LOGGER.info(
                "Updated existing comment for PR #%s (bug_found - new reproducer)",
                pr_update.pr.number,
            )

            if pr_update.pr.author_login != service_login:
                try:
                    await github.create_request_changes_review(
                        pr_update.pr.number,
                        REVIEW_REQUEST_BODY.format(comment_url=updated.html_url),
                    )
                    LOGGER.info("Requested changes for PR #%s", pr_update.pr.number)
                except Exception:
                    LOGGER.exception(
                        "Failed to request changes for PR #%s", pr_update.pr.number
                    )
        return

    if reproducer is None:
        return

    body = make_comment_body(CommentState.BUG_FOUND, reproducer)
    state.save_reproducer(pr_update.pr.number, reproducer)
    created = await github.create_issue_comment(pr_update.pr.number, body)
    state.save_comment(pr_update.pr.number, created.id, created.html_url)
    LOGGER.info("Created new comment for PR #%s (bug_found)", pr_update.pr.number)

    if pr_update.pr.author_login != service_login:
        try:
            await github.create_request_changes_review(
                pr_update.pr.number,
                REVIEW_REQUEST_BODY.format(comment_url=created.html_url),
            )
            LOGGER.info("Requested changes for PR #%s", pr_update.pr.number)
        except Exception:
            LOGGER.exception(
                "Failed to request changes for PR #%s", pr_update.pr.number
            )
